name: Docker CI/CD to GCP

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate application.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_YML }}" > src/main/resources/application.yml

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Spring Boot app (JAR)
        run: ./gradlew build --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tokkit-server-admin:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tokkit-server-admin:latest

      - name: SSH to GCP and deploy container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop tokkit-server-admin || true
            docker rm tokkit-server-admin || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/tokkit-server-admin:latest
            docker run -d \
              --name tokkit-server-admin \
              -p 8080:8080 \
              --memory=512m \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/tokkit-server-admin:latest
